export const DRIVER_SIGNUP_STARTED = 'DRIVER_SIGNUP_STARTED'
export const DRIVER_SIGNUP_SUCCESS = 'DRIVER_SIGNUP_SUCCESS'
export const DRIVER_SIGNUP_FAILURE = 'DRIVER_SIGNUP_FAILURE'

export const DRIVER_LOGIN_STARTED = 'DRIVER_LOGIN_STARTED'
export const DRIVER_LOGIN_SUCCESS = 'DRIVER_LOGIN_SUCCESS'
export const DRIVER_LOGIN_FAILURE = 'DRIVER_LOGIN_FAILURE'

export const UPDATE_LOCATION_STARTED = 'UPDATE_LOCATION_STARTED'
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS'
export const UPDATE_LOCATION_FAILURE = 'UPDATE_LOCATION_FAILURE'

export const UPDATE_PROFILE_STARTED = 'UPDATE_PROFILE_STARTED'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE'


// RIDER

export const RIDER_SIGNUP_STARTED = 'RIDER_SIGNUP_STARTED'
export const RIDER_SIGNUP_SUCCESS = 'RIDER_SIGNUP_SUCCESS'
export const RIDER_SIGNUP_FAILURE = 'RIDER_SIGNUP_FAILURE'

export const RIDER_LOGIN_STARTED = 'RIDER_LOGIN_STARTED'
export const RIDER_LOGIN_SUCCESS = 'RIDER_LOGIN_SUCCESS'
export const RIDER_LOGIN_FAILURE = 'RIDER_LOGIN_FAILURE'

export const LOGOUT_USER = 'LOGOUT_USER'

export const FIND_DRIVERS_NEARBY_STARTED = 'FIND_DRIVERS_NEARBY_STARTED'
export const FIND_DRIVERS_NEARBY_SUCCESS = 'FIND_DRIVERS_NEARBY_SUCCESS'
export const FIND_DRIVERS_NEARBY_FAILURE = 'FIND_DRIVERS_NEARBY_FAILURE'

export const FIND_DRIVER_BY_ID_STARTED = 'FIND_DRIVER_BY_ID_STARTED'
export const FIND_DRIVER_BY_ID_SUCCESS = 'FIND_DRIVER_BY_ID_SUCCESS'
export const FIND_DRIVER_BY_ID_FAILURE = 'FIND_DRIVER_BY_ID_FAILURE'

export const SEND_TRIP_REQUEST_STARTED = 'SEND_TRIP_REQUEST_STARTED'
export const SEND_TRIP_REQUEST_SUCCESS = 'SEND_TRIP_REQUEST_SUCCESS'
export const SEND_TRIP_REQUEST_FAILURE = 'SEND_TRIP_REQUEST_FAILURE'

export const UPDATE_RIDER_PROFILE_STARTED = 'UPDATE_RIDER_PROFILE_STARTED'
export const UPDATE_RIDER_PROFILE_SUCCESS = 'UPDATE_RIDER_PROFILE_SUCCESS'
export const UPDATE_RIDER_PROFILE_FAILURE = 'UPDATE_RIDER_PROFILE_FAILURE'

export const SUBMIT_DRIVER_REVIEW_STARTED = 'SUBMIT_DRIVER_REVIEW_STARTED'
export const SUBMIT_DRIVER_REVIEW_SUCCESS = 'SUBMIT_DRIVER_REVIEW_SUCCESS'
export const SUBMIT_DRIVER_REVIEW_FAILURE = 'SUBMIT_DRIVER_REVIEW_FAILURE'

export const SUBMIT_RIDER_REVIEW_STARTED = 'SUBMIT_RIDER_REVIEW_STARTED'
export const SUBMIT_RIDER_REVIEW_SUCCESS = 'SUBMIT_RIDER_REVIEW_SUCCESS'
export const SUBMIT_RIDER_REVIEW_FAILURE = 'SUBMIT_RIDER_REVIEW_FAILURE'

export const CANCEL_TRIP_REQUEST = 'CANCEL_TRIP_REQUEST'

export const CONFIRM_TRIP_REQUEST = 'CONFIRM_TRIP_REQUEST'
export const OPEN_MODAL = 'OPEN_MODAL'
export const TOGGLE_RESET_TRIP = 'TOGGLE_RESET_TRIP'
